### ISSUE TITLE
Extract firmware feature not works and crash Atmosphere

### ISSUE THREAD

**Issue by nimaskji** [PoloNX/AtmoPackUpdater#12]
When dopwnloading firmware in applet mode and when the extract process begin, the app crash

**Comment by PoloNX** [comment]
Can you try without applet mode ? If you have the same error I'll investigate about it. 

Else I can make a warning page if you launch the home few with the applet mode or decrease the buffer about the extraction

**Comment by PoloNX** [comment]
> Hello, same crash for me trying extracting firmware without applet mode.

Hi, I'll investigate everything this week-end. Thanks for your report. It crash after the download ?

**Comment by PoloNX** [comment]
I disabled temporally the firmware tab

**Comment by pverdu-kuorum** [comment]
> > Hello, same crash for me trying extracting firmware without applet mode.
> 
> Hi, I'll investigate everything this week-end. Thanks for your report. It crash after the download ?

Yes, I think it's crashing when the app tries to unzip the firmware into firmware folder.

**Comment by PoloNX** [comment]
I fixed this issue in the last commit
