### ISSUE TITLE
Dowload/Update homebrews in their respective folder

### ISSUE THREAD

**Issue by Radder124** [PoloNX/AtmoPackUpdater#16]
When downloading or updating homebrews (like DBI for example), they are added in the "switch" folder of the SD card: /switch/DBI.nro. Would it be possible to do that in their respective folder (like /switch/DBI/DBI.nro)?

Thanks!

**Comment by PoloNX** [comment]
sure. I'll try to do it

**Comment by PoloNX** [comment]
Hi @Radder124, I did a commit on the branch "homebrew_path". Can you try the build here please : https://github.com/PoloNX/AtmoPackUpdater/actions/runs/5985165961

**Comment by Radder124** [comment]
Hi, it works when the folder does not already exist, otherwise it throws an AMS error. But thanks already! :)

**Comment by PoloNX** [comment]
I'll Check after. I don't have my Switch to test. Thx for your feedback

**Comment by PoloNX** [comment]
I tried to fix it : https://github.com/PoloNX/AtmoPackUpdater/actions/runs/5992267459

**Comment by Radder124** [comment]
Yep, it works but both options are creating the /switch/NROfolder/zzz.nro now.

**Comment by Lamcza** [comment]
is it supported on 16.0.3 becouse it gives me atmo crash in applet and just error in normal mode ?

**Comment by PoloNX** [comment]
> is it supported on 16.0.3 and lastes atmo becouse it gives me atmo crash in applet and just error "Unable to start software" in normal mode ?

I'll try to do it in the hour

**Comment by Lamcza** [comment]
> > is it supported on 16.0.3 and lastes atmo becouse it gives me atmo crash in applet and just error "Unable to start software" in normal mode ?
> 
> I'll try to do it in the hour

older version is workin fine :P but i update firm to 16.1.0 so perhaps i will check the newest again later

**Comment by PoloNX** [comment]
I have one crash too. I'll deploy a fix

**Comment by PoloNX** [comment]
pushed a new commit. It works fine for me

**Comment by PoloNX** [comment]
https://github.com/PoloNX/AtmoPackUpdater/actions/runs/6099370642 

@Lamcza @Radder124 can you test ?

**Comment by Lamcza** [comment]
> https://github.com/PoloNX/AtmoPackUpdater/actions/runs/6099370642
> 
> @Lamcza @Radder124 can you test ?

still quacked up crushing on start

**Comment by PoloNX** [comment]
when you start the homebrew ?

**Comment by Lamcza** [comment]
> when you start the homebrew ?

yep in full ram mode wifi on

**Comment by PoloNX** [comment]
Uh, It works for me :(

Do you have one custom dns like for lan play ?

**Comment by Lamcza** [comment]
> Uh, It works for me :(
> 
> Do you have one custom dns like for lan play ?

yea iam using custom dns

**Comment by PoloNX** [comment]
try without

**Comment by Lamcza** [comment]
> try without
same

**Comment by Radder124** [comment]
> https://github.com/PoloNX/AtmoPackUpdater/actions/runs/6099370642
> 
> @Lamcza @Radder124 can you test ?

It seems to work! thanks :)

**Comment by PoloNX** [comment]
> > try without
> 
> same and like i said older one 1.8 is working fine even on 16.1.0
> 
> edit: so it is working fine up to 1.8.2 from 1.9.0 it is crushing

I’ll try to investigate about this weird issue

**Comment by Lamcza** [comment]
> > https://github.com/PoloNX/AtmoPackUpdater/actions/runs/6099370642
> > @Lamcza @Radder124 can you test ?
> 
> It seems to work! thanks :)

on what firmware are you?

**Comment by Radder124** [comment]
> > > https://github.com/PoloNX/AtmoPackUpdater/actions/runs/6099370642
> > > @Lamcza @Radder124 can you test ?
> > 
> > 
> > It seems to work! thanks :)
> 
> on what firmware are you?

16.0.2 / AMS 1.5.2

**Comment by Lamcza** [comment]
> > > > https://github.com/PoloNX/AtmoPackUpdater/actions/runs/6099370642
> > > > @Lamcza @Radder124 can you test ?
> > > 
> > > 
> > > It seems to work! thanks :)
> > 
> > 
> > on what firmware are you?
> 
> 16.0.2 / AMS 1.5.2

i will not ask you to update but if you ever do it let us know if it is working on 16.0.3 or 16.1.0 on 1.5.5 ams
